#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SG50.Resource", IsApplication=true)]

namespace SG50
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::FacebookMonoDroid.Resource.String.library_name = global::SG50.Resource.String.library_name;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int in_from_left = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int in_from_right = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int out_to_left = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int out_to_right = 2130968579;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bg = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int camera_icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int flag = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int home = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int indicator_input_error = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int logo = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int monoandroidsplash = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int popup_inline_error = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int presenticon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int progress1 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int progress2 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int progress3 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int progress4 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int step1 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int step2 = 2130837519;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070033
			public const int BTN_Continue1 = 2131165235;
			
			// aapt resource value: 0x7f070037
			public const int BTN_Continue2 = 2131165239;
			
			// aapt resource value: 0x7f07003b
			public const int BTN_Continue3 = 2131165243;
			
			// aapt resource value: 0x7f07003f
			public const int BTN_Continue4 = 2131165247;
			
			// aapt resource value: 0x7f070044
			public const int BTN_Continue5 = 2131165252;
			
			// aapt resource value: 0x7f070047
			public const int BTN_Continue6 = 2131165255;
			
			// aapt resource value: 0x7f07001b
			public const int BTN_FINISH = 2131165211;
			
			// aapt resource value: 0x7f07000a
			public const int BTN_FLAG = 2131165194;
			
			// aapt resource value: 0x7f070008
			public const int BTN_LIKE = 2131165192;
			
			// aapt resource value: 0x7f070028
			public const int BTN_LOGIN = 2131165224;
			
			// aapt resource value: 0x7f070029
			public const int BTN_SIGNUP = 2131165225;
			
			// aapt resource value: 0x7f070004
			public const int BTN_play = 2131165188;
			
			// aapt resource value: 0x7f070027
			public const int ButtonPlacerholder = 2131165223;
			
			// aapt resource value: 0x7f070045
			public const int ConfirmMessage = 2131165253;
			
			// aapt resource value: 0x7f070038
			public const int EMAILLACEHOLDER = 2131165240;
			
			// aapt resource value: 0x7f07000d
			public const int FirstScreen = 2131165197;
			
			// aapt resource value: 0x7f070005
			public const int FlagsAndLikesPlaceHolder = 2131165189;
			
			// aapt resource value: 0x7f070009
			public const int FlagsPlaceHolder = 2131165193;
			
			// aapt resource value: 0x7f070018
			public const int FourthScreen = 2131165208;
			
			// aapt resource value: 0x7f07002b
			public const int GridHolder = 2131165227;
			
			// aapt resource value: 0x7f070034
			public const int HANDPHONEPLACERHOLDER = 2131165236;
			
			// aapt resource value: 0x7f070006
			public const int LikesPlaceHolder = 2131165190;
			
			// aapt resource value: 0x7f07001e
			public const int LogoContainer = 2131165214;
			
			// aapt resource value: 0x7f07002e
			public const int MainContainer = 2131165230;
			
			// aapt resource value: 0x7f07002f
			public const int NRICPLACEHOLDER = 2131165231;
			
			// aapt resource value: 0x7f070040
			public const int PASSWORDPLACEHOLDER = 2131165248;
			
			// aapt resource value: 0x7f070023
			public const int PasswordPlaceholder = 2131165219;
			
			// aapt resource value: 0x7f070011
			public const int SecondScreen = 2131165201;
			
			// aapt resource value: 0x7f070039
			public const int TV_EMAIL = 2131165241;
			
			// aapt resource value: 0x7f070026
			public const int TV_FORGOTPASSWORD = 2131165222;
			
			// aapt resource value: 0x7f070035
			public const int TV_HP = 2131165237;
			
			// aapt resource value: 0x7f070007
			public const int TV_LIKES = 2131165191;
			
			// aapt resource value: 0x7f070030
			public const int TV_NRIC = 2131165232;
			
			// aapt resource value: 0x7f070024
			public const int TV_PASSWORD = 2131165220;
			
			// aapt resource value: 0x7f070001
			public const int TV_POSTED = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int TV_TITLE = 2131165184;
			
			// aapt resource value: 0x7f070021
			public const int TV_USERNAME = 2131165217;
			
			// aapt resource value: 0x7f070046
			public const int TV_dob = 2131165254;
			
			// aapt resource value: 0x7f070041
			public const int TV_password = 2131165249;
			
			// aapt resource value: 0x7f07003d
			public const int TV_username = 2131165245;
			
			// aapt resource value: 0x7f07003c
			public const int USERNAMEPLACEHOLDER = 2131165244;
			
			// aapt resource value: 0x7f070020
			public const int UsernamePlaceholder = 2131165216;
			
			// aapt resource value: 0x7f070002
			public const int VideoPlaceHolder = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int VideoPlayer = 2131165187;
			
			// aapt resource value: 0x7f07000c
			public const int ViewSwitcher = 2131165196;
			
			// aapt resource value: 0x7f07002d
			public const int btnCamera = 2131165229;
			
			// aapt resource value: 0x7f070022
			public const int ed_loginUser = 2131165218;
			
			// aapt resource value: 0x7f070025
			public const int ed_loginpass = 2131165221;
			
			// aapt resource value: 0x7f070032
			public const int et_NRIC = 2131165234;
			
			// aapt resource value: 0x7f07003a
			public const int et_email = 2131165242;
			
			// aapt resource value: 0x7f07003e
			public const int et_name = 2131165246;
			
			// aapt resource value: 0x7f070042
			public const int et_password = 2131165250;
			
			// aapt resource value: 0x7f070036
			public const int et_phone = 2131165238;
			
			// aapt resource value: 0x7f070043
			public const int et_repassword = 2131165251;
			
			// aapt resource value: 0x7f07000b
			public const int linearLayout1 = 2131165195;
			
			// aapt resource value: 0x7f07001f
			public const int logo = 2131165215;
			
			// aapt resource value: 0x7f07001d
			public const int maincontainer = 2131165213;
			
			// aapt resource value: 0x7f07002a
			public const int maincontent = 2131165226;
			
			// aapt resource value: 0x7f07002c
			public const int menubar = 2131165228;
			
			// aapt resource value: 0x7f07001a
			public const int presenttext = 2131165210;
			
			// aapt resource value: 0x7f070010
			public const int progress1 = 2131165200;
			
			// aapt resource value: 0x7f070014
			public const int progress2 = 2131165204;
			
			// aapt resource value: 0x7f070017
			public const int progress3 = 2131165207;
			
			// aapt resource value: 0x7f07001c
			public const int progress4 = 2131165212;
			
			// aapt resource value: 0x7f07000e
			public const int screen1 = 2131165198;
			
			// aapt resource value: 0x7f070012
			public const int screen2 = 2131165202;
			
			// aapt resource value: 0x7f070015
			public const int screen3 = 2131165205;
			
			// aapt resource value: 0x7f070019
			public const int screen4 = 2131165209;
			
			// aapt resource value: 0x7f070013
			public const int step1text = 2131165203;
			
			// aapt resource value: 0x7f070016
			public const int step3text = 2131165206;
			
			// aapt resource value: 0x7f070031
			public const int textView1 = 2131165233;
			
			// aapt resource value: 0x7f070048
			public const int view1 = 2131165256;
			
			// aapt resource value: 0x7f07000f
			public const int welcometext = 2131165199;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int FeedsItem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Intro = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int login = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int register = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int splash = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int welcome = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Mono_Android_Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
